<?php
session_start();
include("../config/db.php");
include("../config/functions.php");


error_reporting(E_ALL);
ini_set('display_errors',1);

/* AUTH */
if(!isset($_SESSION['user_id']) || ($_SESSION['role']??'')!='suggestion_manager'){
    header("Location: ../login.php");
    exit();
}

/* ================= TCPDF ================= */
require_once('/usr/share/php/tcpdf/tcpdf.php');

if(!class_exists('TCPDF')){
    die("TCPDF not installed correctly");
}

/* ================= GET FILTERS ================= */
$from_date = $_GET['from'] ?? date('Y-m-01');
$to_date = $_GET['to'] ?? date('Y-m-d');

/* ================= DATA WITH FILTERS ================= */

$total_query = "SELECT COUNT(*) total FROM suggestions WHERE DATE(created_at) BETWEEN '$from_date' AND '$to_date'";
$total = $conn->query($total_query)->fetch_assoc()['total'] ?? 0;

$pending_query = "SELECT COUNT(*) total FROM suggestions WHERE status='pending' AND DATE(created_at) BETWEEN '$from_date' AND '$to_date'";
$pending = $conn->query($pending_query)->fetch_assoc()['total'] ?? 0;

$approved_query = "SELECT COUNT(*) total FROM suggestions WHERE status='approved' AND DATE(created_at) BETWEEN '$from_date' AND '$to_date'";
$approved = $conn->query($approved_query)->fetch_assoc()['total'] ?? 0;

$rejected_query = "SELECT COUNT(*) total FROM suggestions WHERE status='rejected' AND DATE(created_at) BETWEEN '$from_date' AND '$to_date'";
$rejected = $conn->query($rejected_query)->fetch_assoc()['total'] ?? 0;

$implemented_query = "SELECT COUNT(*) total FROM suggestions WHERE status='implemented' AND DATE(created_at) BETWEEN '$from_date' AND '$to_date'";
$implemented = $conn->query($implemented_query)->fetch_assoc()['total'] ?? 0;

/* ================= PDF GENERATION ================= */
if(isset($_GET['pdf'])){

    $pdf = new TCPDF('P', 'mm', 'A4');
    $pdf->SetCreator("Digital Suggestion Box");
    $pdf->SetAuthor("Digital Suggestion Box System");
    $pdf->SetTitle("Suggestion Report");
    $pdf->SetSubject("Suggestion Report");
    $pdf->SetKeywords("Suggestion, Report, Digital Suggestion Box");

    $pdf->SetHeaderData('', 0, 'Digital Suggestion Box System', 'Suggestion Report');
    $pdf->setHeaderFont(Array('helvetica', '', 12));
    $pdf->setFooterFont(Array('helvetica', '', 10));

    $pdf->SetDefaultMonospacedFont('courier');
    $pdf->SetMargins(15, 25, 15);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(TRUE, 25);

    $pdf->AddPage();
    $pdf->SetFont('helvetica', '', 11);

    // ================= HEADER =================
    $html = "
    <div style='text-align:center;'>
        <h1 style='color:#111827;'>Digital Suggestion Box System</h1>
        <h3 style='color:#2563eb;'>Suggestion Report</h3>
        <p style='color:#64748b;'>
            <strong>Report Period:</strong> " . date('F j, Y', strtotime($from_date)) . " - " . date('F j, Y', strtotime($to_date)) . "<br>
            <strong>Generated:</strong> " . date('F j, Y g:i A') . "<br>
            <strong>Generated By:</strong> " . htmlspecialchars($_SESSION['full_name'] ?? 'Manager') . "
        </p>
        <hr style='border:1px solid #e2e8f0;'>
    </div>
    <br>
    ";

    // ================= SUMMARY STATISTICS =================
    $html .= "
    <h3 style='color:#111827;'>Summary Statistics</h3>
    <table border='1' cellpadding='8' style='border-collapse:collapse; width:100%;'>
        <tr style='background:#111827; color:white;'>
            <th style='padding:10px;'>Total Suggestions</th>
            <th style='padding:10px;'>Pending</th>
            <th style='padding:10px;'>Approved</th>
            <th style='padding:10px;'>Rejected</th>
            <th style='padding:10px;'>Implemented</th>
        </tr>
        <tr style='text-align:center;'>
            <td style='padding:10px; font-size:18px; font-weight:bold; color:#2563eb;'>$total</td>
            <td style='padding:10px; font-size:18px; font-weight:bold; color:#f59e0b;'>$pending</td>
            <td style='padding:10px; font-size:18px; font-weight:bold; color:#22c55e;'>$approved</td>
            <td style='padding:10px; font-size:18px; font-weight:bold; color:#ef4444;'>$rejected</td>
            <td style='padding:10px; font-size:18px; font-weight:bold; color:#3b82f6;'>$implemented</td>
        </tr>
    </table>
    <br>
    ";

    // ================= STATUS PERCENTAGE =================
    $total_all = $total > 0 ? $total : 1;
    $pending_percent = round(($pending / $total_all) * 100);
    $approved_percent = round(($approved / $total_all) * 100);
    $rejected_percent = round(($rejected / $total_all) * 100);
    $implemented_percent = round(($implemented / $total_all) * 100);

    $html .= "
    <h3 style='color:#111827;'>Status Distribution</h3>
    <table border='1' cellpadding='6' style='border-collapse:collapse; width:100%;'>
        <tr style='background:#111827; color:white;'>
            <th style='padding:8px;'>Status</th>
            <th style='padding:8px;'>Count</th>
            <th style='padding:8px;'>Percentage</th>
        </tr>
        <tr>
            <td style='padding:8px;'>Pending</td>
            <td style='padding:8px; text-align:center;'>$pending</td>
            <td style='padding:8px; text-align:center;'>$pending_percent%</td>
        </tr>
        <tr>
            <td style='padding:8px;'>Approved</td>
            <td style='padding:8px; text-align:center;'>$approved</td>
            <td style='padding:8px; text-align:center;'>$approved_percent%</td>
        </tr>
        <tr>
            <td style='padding:8px;'>Rejected</td>
            <td style='padding:8px; text-align:center;'>$rejected</td>
            <td style='padding:8px; text-align:center;'>$rejected_percent%</td>
        </tr>
        <tr>
            <td style='padding:8px;'>Implemented</td>
            <td style='padding:8px; text-align:center;'>$implemented</td>
            <td style='padding:8px; text-align:center;'>$implemented_percent%</td>
        </tr>
    </table>
    <br>
    ";

    // ================= SUGGESTIONS PER CATEGORY =================
    $categories = $conn->query("
    SELECT 
        c.category_name,
        COUNT(s.suggestion_id) as total
    FROM categories c
    LEFT JOIN suggestions s ON s.category_id = c.category_id
        AND DATE(s.created_at) BETWEEN '$from_date' AND '$to_date'
    GROUP BY c.category_id
    ORDER BY total DESC
    ");

    $html .= "
    <h3 style='color:#111827;'>Suggestions by Category</h3>
    <table border='1' cellpadding='6' style='border-collapse:collapse; width:100%;'>
        <tr style='background:#111827; color:white;'>
            <th style='padding:8px;'>Category</th>
            <th style='padding:8px;'>Total</th>
        </tr>
    ";

    if($categories && $categories->num_rows > 0){
        while($row = $categories->fetch_assoc()){
            $html .= "
            <tr>
                <td style='padding:8px;'>".htmlspecialchars($row['category_name'])."</td>
                <td style='padding:8px; text-align:center;'>{$row['total']}</td>
            </tr>
            ";
        }
    } else {
        $html .= "
        <tr>
            <td colspan='2' style='padding:8px; text-align:center; color:#94a3b8;'>No categories found</td>
        </tr>
        ";
    }
    $html .= "</table><br>";

    // ================= TOP CONTRIBUTORS =================
    $contributors = $conn->query("
    SELECT 
        u.full_name,
        COUNT(s.suggestion_id) as total
    FROM users u
    LEFT JOIN suggestions s ON s.user_id = u.user_id
        AND DATE(s.created_at) BETWEEN '$from_date' AND '$to_date'
    WHERE u.role = 'suggester'
    GROUP BY u.user_id
    ORDER BY total DESC
    LIMIT 10
    ");

    $html .= "
    <h3 style='color:#111827;'>Top Contributors</h3>
    <table border='1' cellpadding='6' style='border-collapse:collapse; width:100%;'>
        <tr style='background:#111827; color:white;'>
            <th style='padding:8px;'>Rank</th>
            <th style='padding:8px;'>User</th>
            <th style='padding:8px;'>Suggestions</th>
        </tr>
    ";

    if($contributors && $contributors->num_rows > 0){
        $rank = 1;
        while($row = $contributors->fetch_assoc()){
            $html .= "
            <tr>
                <td style='padding:8px; text-align:center;'>{$rank}</td>
                <td style='padding:8px;'>".htmlspecialchars($row['full_name'])."</td>
                <td style='padding:8px; text-align:center;'>{$row['total']}</td>
            </tr>
            ";
            $rank++;
        }
    } else {
        $html .= "
        <tr>
            <td colspan='3' style='padding:8px; text-align:center; color:#94a3b8;'>No contributors found</td>
        </tr>
        ";
    }
    $html .= "</table><br>";

    // ================= ALL SUGGESTIONS LIST =================
    $suggestions = $conn->query("
    SELECT 
        s.suggestion_id,
        s.title,
        s.message,
        s.status,
        s.created_at,
        u.full_name,
        c.category_name
    FROM suggestions s
    JOIN users u ON u.user_id = s.user_id
    LEFT JOIN categories c ON c.category_id = s.category_id
    WHERE DATE(s.created_at) BETWEEN '$from_date' AND '$to_date'
    ORDER BY s.created_at DESC
    LIMIT 50
    ");

    $html .= "
    <h3 style='color:#111827;'>Recent Suggestions (Last 50)</h3>
    <table border='1' cellpadding='5' style='border-collapse:collapse; width:100%; font-size:9px;'>
        <tr style='background:#111827; color:white;'>
            <th style='padding:6px;'>ID</th>
            <th style='padding:6px;'>Title</th>
            <th style='padding:6px;'>Category</th>
            <th style='padding:6px;'>Status</th>
            <th style='padding:6px;'>Submitted By</th>
            <th style='padding:6px;'>Date</th>
        </tr>
    ";

    if($suggestions && $suggestions->num_rows > 0){
        while($row = $suggestions->fetch_assoc()){
            $status_color = match($row['status']) {
                'pending' => '#f59e0b',
                'approved' => '#22c55e',
                'rejected' => '#ef4444',
                'implemented' => '#3b82f6',
                default => '#64748b'
            };
            
            $html .= "
            <tr>
                <td style='padding:6px; text-align:center;'>{$row['suggestion_id']}</td>
                <td style='padding:6px;'>".htmlspecialchars(substr($row['title'], 0, 30))."</td>
                <td style='padding:6px;'>".htmlspecialchars($row['category_name'] ?? 'N/A')."</td>
                <td style='padding:6px; text-align:center;'>
                    <span style='background:{$status_color}; color:white; padding:2px 8px; border-radius:999px; font-size:8px;'>
                        ".ucfirst($row['status'])."
                    </span>
                </td>
                <td style='padding:6px;'>".htmlspecialchars($row['full_name'])."</td>
                <td style='padding:6px; text-align:center;'>".date('M j, Y', strtotime($row['created_at']))."</td>
            </tr>
            ";
        }
    } else {
        $html .= "
        <tr>
            <td colspan='6' style='padding:8px; text-align:center; color:#94a3b8;'>No suggestions found for this period</td>
        </tr>
        ";
    }
    $html .= "</table><br>";

    // ================= FOOTER =================
    $html .= "
    <hr style='border:1px solid #e2e8f0;'>
    <p style='text-align:center; color:#94a3b8; font-size:9px;'>
        This report was generated automatically by Digital Suggestion Box System.<br>
        Report Period: " . date('F j, Y', strtotime($from_date)) . " - " . date('F j, Y', strtotime($to_date)) . "<br>
        Generated: " . date('F j, Y g:i A') . "<br>
        Page {PAGE_NUM} of {PAGE_COUNT}
    </p>
    ";

    $pdf->writeHTML($html, true, false, true, false, '');
    $pdf->Output("suggestion_report_" . date('Y-m-d') . ".pdf", "I");
    exit();
}

?>

<!DOCTYPE html>
<html>
<head>
<title>Reports</title>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

<style>
body{
    margin:0;
    font-family:Segoe UI, sans-serif;
    background:#f4f7fb;
    color:#1e293b;
}

.content{
    margin-left:250px;
    padding:30px;
    padding-top:100px;
    min-height:calc(100vh - 180px);
}

.header-actions{
    display:flex;
    justify-content:space-between;
    align-items:center;
    flex-wrap:wrap;
    gap:15px;
    margin-bottom:20px;
}

.header-actions h2{
    margin:0;
    color:#111827;
}

.cards{
    display:grid;
    grid-template-columns:repeat(5,1fr);
    gap:18px;
    margin-bottom:25px;
}

.card{
    padding:22px;
    border-radius:16px;
    text-align:center;
    background:white;
    border:1px solid #e2e8f0;
    box-shadow:0 8px 20px rgba(15,23,42,.08);
    transition:transform 0.2s;
}

.card:hover{
    transform:translateY(-3px);
}

.card h2{
    font-size:30px;
    margin:0;
    color:#0f172a;
}

.card p{
    margin:5px 0 0;
    color:#64748b;
    font-weight:500;
}

.card-total{ border-top:4px solid #111827; }
.card-pending{ border-top:4px solid #f59e0b; }
.card-approved{ border-top:4px solid #22c55e; }
.card-rejected{ border-top:4px solid #ef4444; }
.card-implemented{ border-top:4px solid #3b82f6; }

.filter-box{
    background:white;
    padding:20px;
    border-radius:16px;
    border:1px solid #e2e8f0;
    margin-bottom:25px;
    display:flex;
    gap:15px;
    align-items:flex-end;
    flex-wrap:wrap;
}

.filter-box .form-group{
    display:flex;
    flex-direction:column;
    gap:5px;
}

.filter-box label{
    font-size:12px;
    font-weight:600;
    color:#64748b;
}

.filter-box input{
    padding:10px 14px;
    border-radius:8px;
    border:1px solid #cbd5e1;
    font-size:14px;
}

.filter-box .btn-primary{
    background:#111827;
    color:white;
    border:none;
    padding:10px 24px;
    border-radius:8px;
    cursor:pointer;
    font-weight:600;
    transition:background 0.2s;
}

.filter-box .btn-primary:hover{
    background:#1f2937;
}

.report-btn{
    display:inline-block;
    background:#dc2626;
    padding:12px 22px;
    border-radius:10px;
    color:white;
    text-decoration:none;
    font-weight:600;
    transition:background 0.2s;
}

.report-btn:hover{
    background:#b91c1c;
}

@media(max-width:900px){
    .content{
        margin-left:0;
    }
    .cards{
        grid-template-columns:repeat(2,1fr);
    }
    .filter-box{
        flex-direction:column;
        align-items:stretch;
    }
}

@media(max-width:600px){
    .cards{
        grid-template-columns:1fr;
    }
    .header-actions{
        flex-direction:column;
        align-items:flex-start;
    }
}
</style>
</head>

<body>

<?php include("../sider/sider.php"); ?>
<?php include("../toper/toper.php"); ?>

<div class="content">

    <div class="header-actions">
        <h2><i class="fas fa-chart-line" style="color:#2563eb;"></i> Suggestion Reports</h2>
        <a class="report-btn" href="?pdf=1&from=<?= $from_date ?>&to=<?= $to_date ?>">
            <i class="fas fa-file-pdf"></i> Generate PDF
        </a>
    </div>

    <div class="filter-box">
        <div class="form-group">
            <label><i class="fas fa-calendar-alt"></i> From Date</label>
            <input type="date" name="from" value="<?= $from_date ?>" id="from_date">
        </div>
        <div class="form-group">
            <label><i class="fas fa-calendar-alt"></i> To Date</label>
            <input type="date" name="to" value="<?= $to_date ?>" id="to_date">
        </div>
        <button class="btn-primary" onclick="applyFilter()">
            <i class="fas fa-filter"></i> Apply Filter
        </button>
    </div>

    <div class="cards">
        <div class="card card-total">
            <h2><?= $total ?></h2>
            <p>Total Suggestions</p>
        </div>
        <div class="card card-pending">
            <h2><?= $pending ?></h2>
            <p>Pending</p>
        </div>
        <div class="card card-approved">
            <h2><?= $approved ?></h2>
            <p>Approved</p>
        </div>
        <div class="card card-rejected">
            <h2><?= $rejected ?></h2>
            <p>Rejected</p>
        </div>
        <div class="card card-implemented">
            <h2><?= $implemented ?></h2>
            <p>Implemented</p>
        </div>
    </div>

</div>

<script>
function applyFilter(){
    var from = document.getElementById('from_date').value;
    var to = document.getElementById('to_date').value;
    if(from && to){
        window.location.href = '?from=' + from + '&to=' + to;
    }
}

document.addEventListener('DOMContentLoaded', function(){
    var from = document.getElementById('from_date');
    var to = document.getElementById('to_date');
    if(!from.value){
        var d = new Date();
        d.setDate(1);
        from.value = d.toISOString().split('T')[0];
    }
    if(!to.value){
        var d = new Date();
        to.value = d.toISOString().split('T')[0];
    }
});
</script>

<?php include("../footer/footer.php"); ?>

</body>
</html>